// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:f615fec5-35fb-433f-981d-f05bd0ed41da",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_VAYKTyzRJ",
    "aws_user_pools_web_client_id": "3k91mqq97esg5i2btsklttd303",
    "oauth": {}
};


export default awsmobile;
